/**
 * Monitoring schema, v2.
 *
 * Kept apart from 001_init on purpose: the old `posts` table answered one
 * question ("have I seen this link before?") and that is exactly the question
 * that produced the bug where a 2025 article was mailed out again in 2026,
 * because a link the crawler had never happened to fetch looked new.
 *
 * These tables answer a different question: what did this page SAY last time,
 * and is what it says now different in a way a person would care about.
 *
 *   pages             one row per URL we watch, with its current state
 *   page_versions     the full text each time it changed - never pruned, it
 *                     is what lets Claude compare before and after
 *   detected_changes  one row per verdict, with the audit trail
 *   daily_reports     one row per morning summary
 *
 * Portable between SQLite and Postgres: timestamps are ISO-8601 TEXT and
 * booleans are 0/1, exactly as in 001_init.
 */
export const MONITOR_SCHEMA_NAME = '003_monitor_v2';

export const MONITOR_SCHEMA_POSTGRES = String.raw`
CREATE TABLE IF NOT EXISTS pages (
  id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  website_id         INTEGER NOT NULL REFERENCES websites(id) ON DELETE CASCADE,
  url                TEXT    NOT NULL,
  title              TEXT,
  status             TEXT    NOT NULL DEFAULT 'active',
  discovered_at      TEXT    NOT NULL,
  first_content_at   TEXT,
  last_seen_at       TEXT    NOT NULL,
  last_checked_at    TEXT,
  last_changed_at    TEXT,
  published_at       TEXT,
  modified_at        TEXT,
  text_hash          TEXT,
  char_count         INTEGER NOT NULL DEFAULT 0,
  version_count      INTEGER NOT NULL DEFAULT 0,
  baseline_done      SMALLINT NOT NULL DEFAULT 0,
  consecutive_errors INTEGER NOT NULL DEFAULT 0,
  last_error         TEXT,
  source             TEXT,
  UNIQUE (website_id, url)
);
CREATE INDEX IF NOT EXISTS idx_pages_website ON pages(website_id, status);
CREATE INDEX IF NOT EXISTS idx_pages_changed ON pages(last_changed_at DESC);

CREATE TABLE IF NOT EXISTS page_versions (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_id      INTEGER NOT NULL REFERENCES pages(id) ON DELETE CASCADE,
  captured_at  TEXT    NOT NULL,
  text_hash    TEXT    NOT NULL,
  title        TEXT,
  text         TEXT    NOT NULL,
  char_count   INTEGER NOT NULL DEFAULT 0,
  published_at TEXT,
  modified_at  TEXT,
  source       TEXT
);
CREATE INDEX IF NOT EXISTS idx_versions_page ON page_versions(page_id, captured_at DESC);

CREATE TABLE IF NOT EXISTS detected_changes (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_id           INTEGER REFERENCES pages(id) ON DELETE CASCADE,
  website_id        INTEGER NOT NULL REFERENCES websites(id) ON DELETE CASCADE,
  from_version_id   INTEGER REFERENCES page_versions(id) ON DELETE SET NULL,
  to_version_id     INTEGER REFERENCES page_versions(id) ON DELETE SET NULL,
  detected_at       TEXT    NOT NULL,
  change_date       TEXT    NOT NULL,
  change_type       TEXT    NOT NULL,
  priority          TEXT    NOT NULL DEFAULT 'LOW',
  title             TEXT,
  url               TEXT,
  summary           TEXT,
  what_changed      TEXT,
  previous_value    TEXT,
  new_value         TEXT,
  reasoning         TEXT,
  analyzer          TEXT    NOT NULL DEFAULT 'claude',
  model             TEXT,
  input_tokens      INTEGER NOT NULL DEFAULT 0,
  output_tokens     INTEGER NOT NULL DEFAULT 0,
  cached_tokens     INTEGER NOT NULL DEFAULT 0,
  analysis_input    TEXT,
  analysis_output   TEXT,
  reported_in       INTEGER,
  UNIQUE (to_version_id, page_id)
);
CREATE INDEX IF NOT EXISTS idx_changes_date ON detected_changes(change_date, priority);
CREATE INDEX IF NOT EXISTS idx_changes_website ON detected_changes(website_id, detected_at DESC);
CREATE INDEX IF NOT EXISTS idx_changes_report ON detected_changes(reported_in);

CREATE TABLE IF NOT EXISTS daily_reports (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_date     TEXT    NOT NULL UNIQUE,
  generated_at    TEXT    NOT NULL,
  window_start    TEXT    NOT NULL,
  window_end      TEXT    NOT NULL,
  total_changes   INTEGER NOT NULL DEFAULT 0,
  high_priority   INTEGER NOT NULL DEFAULT 0,
  medium_priority INTEGER NOT NULL DEFAULT 0,
  low_priority    INTEGER NOT NULL DEFAULT 0,
  websites_total  INTEGER NOT NULL DEFAULT 0,
  websites_quiet  INTEGER NOT NULL DEFAULT 0,
  daily_summary   TEXT,
  payload         TEXT    NOT NULL,
  model           TEXT,
  input_tokens    INTEGER NOT NULL DEFAULT 0,
  output_tokens   INTEGER NOT NULL DEFAULT 0,
  sent_at         TEXT,
  recipients      TEXT,
  error           TEXT
);
CREATE INDEX IF NOT EXISTS idx_reports_date ON daily_reports(report_date DESC);
`;

/**
 * Every attempt to send the daily report, kept for ever.
 *
 * `daily_reports.error` holds why THIS date is still undelivered, and a later
 * forced send clears it - which is exactly how a failed 07:00 send became
 * invisible the moment somebody pressed "Enviar ahora". This table is
 * append-only: nothing in the code ever updates or deletes a row, so the
 * dashboard can always answer "what happened this morning?".
 */
export const REPORT_ATTEMPTS_NAME = '004_report_attempts';

export const REPORT_ATTEMPTS_POSTGRES = `
CREATE TABLE IF NOT EXISTS report_attempts (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_date  TEXT    NOT NULL,
  attempted_at TEXT    NOT NULL,
  origin       TEXT    NOT NULL,
  outcome      TEXT    NOT NULL,
  reason       TEXT,
  changes      INTEGER NOT NULL DEFAULT 0,
  recipients   TEXT,
  message_id   TEXT
);
CREATE INDEX IF NOT EXISTS idx_report_attempts_at ON report_attempts(attempted_at DESC);
CREATE INDEX IF NOT EXISTS idx_report_attempts_date ON report_attempts(report_date DESC);
`;

export const REPORT_ATTEMPTS_SQLITE = REPORT_ATTEMPTS_POSTGRES.replace(
  /INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY/g,
  'INTEGER PRIMARY KEY AUTOINCREMENT',
);

/** Same tables, SQLite spelling. Only the identity column differs. */
export const MONITOR_SCHEMA_SQLITE = MONITOR_SCHEMA_POSTGRES.replace(
  /INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY/g,
  'INTEGER PRIMARY KEY AUTOINCREMENT',
).replace(/SMALLINT/g, 'INTEGER');

/**
 * La categoría del cambio y el borrador de mensaje, añadidos a los veredictos.
 *
 * Dos columnas sobre la tabla que ya existe, no una tabla nueva: la categoría
 * es parte del veredicto -la decide el mismo análisis, en la misma llamada- y
 * el borrador es el texto que ese veredicto produce. Separarlos en otra tabla
 * habría significado un JOIN para responder "¿esto entra en el informe?", que
 * es justamente la pregunta que más se hace.
 *
 * Las filas anteriores se quedan con las dos columnas a NULL, que es lo
 * correcto: nunca se clasificaron, y un NULL no es una categoría vacía sino
 * la ausencia de la pregunta. El informe las sigue tratando como siempre.
 */
export const RELEVANCE_NAME = '005_change_relevance';

export const RELEVANCE_POSTGRES = `
ALTER TABLE detected_changes ADD COLUMN IF NOT EXISTS category      TEXT;
ALTER TABLE detected_changes ADD COLUMN IF NOT EXISTS draft_message TEXT;
CREATE INDEX IF NOT EXISTS idx_changes_category ON detected_changes(category);
`;

/**
 * SQLite no admite ADD COLUMN IF NOT EXISTS, pero tampoco lo necesita: el
 * fichero de migración se aplica una sola vez y queda anotado en
 * schema_migrations, así que el ALTER nunca se repite.
 */
export const RELEVANCE_SQLITE = RELEVANCE_POSTGRES.replace(/ ADD COLUMN IF NOT EXISTS/g, ' ADD COLUMN');
